### PR TITLE
Modified macros to respect namespaces.

### PR DESCRIPTION
**Pull request by BeadW**
Upgraded macros per the package maintainers requirements for dispatch https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#for-package-maintainers

### CODE REVIEW

**Comment by BeadW** [comment]
Hi @emilyriederer please let me know if there are any issues with this. Would be good to get this and the change you have made to overview.md into the release on dbt package site to make this play nicer with complex projects.

**Comment by emilyriederer** [comment]
Thanks for the PR, @BeadW ! The CI tests are failing not because of your code but because of a new problem seemingly related to the BQ connection. I'll get to the bottom of that ASAP so we can get this merged. 

Just for my context, I understand dispatch is most useful for extending/overriding functions. Do you have specific use cases for this in mind? I ask just to see if there are more features I should be thinking of adding in the future.

**Comment by BeadW** [comment]
> 

Hi @emilyriederer, I was just working through why the package was causing issues with our docs and essentially looking for how it could be hijacking some upstream functionality. This didn't turn out to be the issue, but I had already changed it in line with the link I put in the PR so I figured it was worth contributing.

**Comment by emilyriederer** [comment]
Thanks again for the PR, @BeadW ! Got the tests up and running again. What I'm encountering now is there is a versioning mismatch between (the versions of dbt / dbt-util that the test suite assumes) and (the min version of dbt that handles dispatches in this way). I'll try to get everything updated to the same spot this weekend and aim to get this merged and released soon

**Comment by emilyriederer** [comment]
Hi @BeadW ! Testing suite is now working but turned up some odd behavior. I wanted to see if you've seen anything like this before or had more intuition as I'm a bit green on the dbt adapter dispatch functionality. 

Your enhancements works great and pass for:

- `where_helpers.sql`
- `across.sql` (after modifying default arg pass-through)
- `map.sql`

However, the enhancements for the rest of the files are throwing very odd errors:

- `select_helpers.sql`
- `get_column_names.sql`
- `get_matches.sql`

As an example, after using the modified version of the `starts_with()` macro, the [`starts_with.sql` model](https://github.com/emilyriederer/dbtplyr/blob/main/integration_tests/models/starts_with.sql) compiles to:

```

select 
,
   ,
   ,
   ,
   ,
  [,
  ',
  a,
  m,
  t,
  _,
  c,
  ',
  ],  
from `sonorous-wharf-302611`.`dbt_emily`.`data`
```

I get the sense that somehow more complex objects than simple strings (e.g. relations, lists) aren't getting passed through correctly. However, looking at some of the `dbt-utils` macros ([example](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/get_column_values.sql)), it doesn't appear they do anything special to handle these datatypes.

I'll keep digging into it, but that's the update.

**Comment by emilyriederer** [comment]
Got this merged! Thanks again so much for the contribution @BeadW . Really glad to have this in there. I have also bumped the version to 0.3.0 and done an official release which is now being [properly reported](https://hub.getdbt.com/emilyriederer/dbtplyr/latest/) on dbthub. So, hopefully this makes the package play nicer with your project!

**Comment by BeadW** [comment]
Thanks @emilyriederer. Apologies I didn't respond sooner it was a long weekend here. Really appreciate your work on this. :)

**Comment by emilyriederer** [comment]
@BeadW - please don't be sorry! I was just documenting as I explored mostly so you knew I wasn't ignoring the PR and in case there was any urgency on your end for your projects. Didn't expect a fast response and happy to know more about adapter dispatch now! 🤓

**Pull request merged**
